services:
  arcadedb:
      image: arcadedata/arcadedb:latest
      container_name: arcadedb
      environment:
        # Define a senha root do ArcadeDB (necessário para a API REST)
        - JAVA_OPTS=-Darcadedb.server.rootPassword=playwithdata
      ports:
        - "2480:2480" # API HTTP / REST
        - "2424:2424" # Porta Binária
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  crm_service:
    build: ./crm_service
    container_name: crm_service
    ports:
      - "8001:8001"

  budget_service:
    build: ./budget_service
    container_name: budget_service
    ports:
      - "8002:8002"

  mcp_server:
    build: ./mcp_server
    container_name: mcp_server
    ports:
      - "8000:8000"
    depends_on:
      - crm_service
      - budget_service

  mcp_client:
    build: ./mcp_client
    container_name: mcp_client
    ports:  
      - "8501:8501" # Porta exposta para acessar a interface Web
    environment:
      - OPENROUTER_API_KEY="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"
      - OPENROUTER_MODEL=google/gemma-4-26b-a4b-it:free   # Escolha seu modelo favorito
    depends_on:
      - mcp_server
      - ollama

  knowledge_service:
    build: ./knowledge_service
    container_name: knowledge_service
    ports:
      - "8003:8003"
    depends_on:
      - neo4j_db

volumes:
  ollama_data: